# bash script

reference=1kg
projectID=Project_Example

# The fastq.gz files used by the aligner have have already been generated by the following command:
# wgsim -N1000 -S1 ../data/truncated_GCA_000001405.15_GRCh38_no_alt_analysis_set.fna ../data/sim_reads_1.fq.gz ../data/sim_reads_2.fq.gz
# This simulates 1000 paired-end reads from ../data/truncated_GCA_000001405.15_GRCh38_no_alt_analysis_set.fna 
# and writes them to ../data/sim_reads_1.fq.gz and to ../data/sim_reads_2.fq.gz

# generate support file by looking .fastq.gz files in ../data/
bash ../makesupport.sh ../data/ .fastq.gz > support.txt

# alignment
bash ../WGS_pipeline.sh --mode align \
                        --supportFrame support.txt \
                        --reference ${reference} \
                        --tparam 320 \
                        --inputFormat STDFQ \
                        --projectID ${projectID} \
                        


